In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\uSER\Downloads\daily_weather.csv")
df

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
0,0,918.060000,74.822000,271.100000,2.080354,295.400000,2.863283,0.0,0.0,42.420000,36.160000
1,1,917.347688,71.403843,101.935179,2.443009,140.471548,3.533324,0.0,0.0,24.328697,19.426597
2,2,923.040000,60.638000,51.000000,17.067852,63.700000,22.100967,0.0,20.0,8.900000,14.460000
3,3,920.502751,70.138895,198.832133,4.337363,211.203341,5.190045,0.0,0.0,12.189102,12.742547
4,4,921.160000,44.294000,277.800000,1.856660,136.500000,2.863283,8.9,14730.0,92.410000,76.740000
...,...,...,...,...,...,...,...,...,...,...,...
1090,1090,918.900000,63.104000,192.900000,3.869906,207.300000,5.212070,0.0,0.0,26.020000,38.180000
1091,1091,918.710000,49.568000,241.600000,1.811921,227.400000,2.371156,0.0,0.0,90.350000,73.340000
1092,1092,916.600000,71.096000,189.300000,3.064608,200.800000,3.892276,0.0,0.0,45.590000,52.310000
1093,1093,912.600000,58.406000,172.700000,3.825167,189.100000,4.764682,0.0,0.0,64.840000,58.280000
1094,1094,921.530000,77.702000,97.100000,3.265932,125.900000,4.451511,0.0,0.0,14.560000,15.100000

In [2]:
df.columns

Index(['number', 'air_pressure_9am', 'air_temp_9am', 'avg_wind_direction_9am',
       'avg_wind_speed_9am', 'max_wind_direction_9am', 'max_wind_speed_9am',
       'rain_accumulation_9am', 'rain_duration_9am', 'relative_humidity_9am',
       'relative_humidity_3pm'],
      dtype='object')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   number                  1095 non-null   int64
 1   air_pressure_9am        1092 non-null   float64
 2   air_temp_9am            1090 non-null   float64
 3   avg_wind_direction_9am  1091 non-null   float64
 4   avg_wind_speed_9am      1092 non-null   float64
 5   max_wind_direction_9am  1092 non-null   float64
 6   max_wind_speed_9am      1091 non-null   float64
 7   rain_accumulation_9am   1089 non-null   float64
 8   rain_duration_9am       1092 non-null   float64
 9   relative_humidity_9am   1095 non-null   float64
 10  relative_humidity_3pm   1095 non-null   float64
dtypes: float64(10), int64(1)
memory usage: 94.2 KB

In [4]:
df.isnull().sum()

number                    0
air_pressure_9am          3
air_temp_9am              5
avg_wind_direction_9am    4
avg_wind_speed_9am        3
max_wind_direction_9am    3
max_wind_speed_9am        4
rain_accumulation_9am     6
rain_duration_9am         3
relative_humidity_9am     0
relative_humidity_3pm     0
dtype: int64

In [5]:
df["air_pressure_9am"]=df["air_pressure_9am"].fillna(df["air_pressure_9am"].mean())
df["air_temp_9am"]=df["air_temp_9am"].fillna(df["air_temp_9am"].mean())
df["avg_wind_direction_9am"]=df["avg_wind_direction_9am"].fillna(df["avg_wind_direction_9am"].mean())
df["avg_wind_speed_9am"]=df["avg_wind_speed_9am"].fillna(df["avg_wind_speed_9am"].mean())
df["max_wind_direction_9am"]=df["max_wind_direction_9am"].fillna(df["max_wind_direction_9am"].mean())
df["max_wind_speed_9am"]=df["max_wind_speed_9am"].fillna(df["max_wind_speed_9am"].mean())
df["rain_accumulation_9am"]=df["rain_accumulation_9am"].fillna(df["rain_accumulation_9am"].mean())
df["rain_duration_9am"]=df["rain_duration_9am"].fillna(df["rain_duration_9am"].mean())

In [6]:
df.isnull().sum()

number                    0
air_pressure_9am          0
air_temp_9am              0
avg_wind_direction_9am    0
avg_wind_speed_9am        0
max_wind_direction_9am    0
max_wind_speed_9am        0
rain_accumulation_9am     0
rain_duration_9am         0
relative_humidity_9am     0
relative_humidity_3pm     0
dtype: int64

In [7]:
clean_df= df.copy()
clean_df["high_humidity_level"]=(df["relative_humidity_3pm"] > 24.99)*1

In [8]:
clean_df

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm,high_humidity_level
0,0,918.060000,74.822000,271.100000,2.080354,295.400000,2.863283,0.0,0.0,42.420000,36.160000,1
1,1,917.347688,71.403843,101.935179,2.443009,140.471548,3.533324,0.0,0.0,24.328697,19.426597,0
2,2,923.040000,60.638000,51.000000,17.067852,63.700000,22.100967,0.0,20.0,8.900000,14.460000,0
3,3,920.502751,70.138895,198.832133,4.337363,211.203341,5.190045,0.0,0.0,12.189102,12.742547,0
4,4,921.160000,44.294000,277.800000,1.856660,136.500000,2.863283,8.9,14730.0,92.410000,76.740000,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1090,918.900000,63.104000,192.900000,3.869906,207.300000,5.212070,0.0,0.0,26.020000,38.180000,1
1091,1091,918.710000,49.568000,241.600000,1.811921,227.400000,2.371156,0.0,0.0,90.350000,73.340000,1
1092,1092,916.600000,71.096000,189.300000,3.064608,200.800000,3.892276,0.0,0.0,45.590000,52.310000,1
1093,1093,912.600000,58.406000,172.700000,3.825167,189.100000,4.764682,0.0,0.0,64.840000,58.280000,1
1094,1094,921.530000,77.702000,97.100000,3.265932,125.900000,4.451511,0.0,0.0,14.560000,15.100000,0

In [9]:
y = clean_df[["high_humidity_level"]].copy()
y.head()

   high_humidity_level
0                    1
1                    0
2                    0
3                    0
4                    1

In [10]:
clean_df[["relative_humidity_3pm"]].head()

   relative_humidity_3pm
0              36.160000
1              19.426597
2              14.460000
3              12.742547
4              76.740000

In [11]:
morning_features = ['air_pressure_9am', 'air_temp_9am', 'avg_wind_direction_9am',
       'avg_wind_speed_9am', 'max_wind_direction_9am', 'max_wind_speed_9am',
       'rain_accumulation_9am', 'rain_duration_9am']

In [12]:
X = clean_df[morning_features].copy()

In [13]:
X.columns

Index(['air_pressure_9am', 'air_temp_9am', 'avg_wind_direction_9am',
       'avg_wind_speed_9am', 'max_wind_direction_9am', 'max_wind_speed_9am',
       'rain_accumulation_9am', 'rain_duration_9am'],
      dtype='object')

In [14]:
X.isna().sum()

air_pressure_9am          0
air_temp_9am              0
avg_wind_direction_9am    0
avg_wind_speed_9am        0
max_wind_direction_9am    0
max_wind_speed_9am        0
rain_accumulation_9am     0
rain_duration_9am         0
dtype: int64

In [15]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.33, random_state = 0)

In [17]:
humidity_classifier = DecisionTreeClassifier(max_leaf_nodes = 10, random_state = 0)
humidity_classifier.fit(X_train,y_train)

DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)

In [18]:
type(humidity_classifier)

sklearn.tree._classes.DecisionTreeClassifier

Prediction

In [19]:
predictions = humidity_classifier.predict(X_test)
predictions[:10]

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [20]:
y_test['high_humidity_level'][:10]

784    1
741    0
747    1
987    0
479    1
27     1
159    1
356    1
320    1
351    1
Name: high_humidity_level, dtype: int32

In [21]:
accuracy_score(y_true = y_test, y_pred = predictions)

0.7955801104972375

In [23]:
data = pd.read_csv(r"C:\Users\uSER\Downloads\avito.csv")
data

,item_id,user_id,region,city,parent_category_name,category_name,param_1,param_2,param_3,title,description,price,item_seq_number,activation_date,user_type,image,image_top_1,deal_probability
0,b912c3c6a6ad,e00f8ff2eaf9,Свердловская область,Екатеринбург,Личные вещи,Товары для детей и игрушки,Постельные принадлежности,NaN,NaN,Кокоби(кокон для сна),"Кокон для сна малыша,пользовались меньше месяц...",400.0,2,2017-03-28,Private,d10c7e016e03247a3bf2d13348fe959fe6f436c1caf64c...,1008.0,0.12789
1,2dac0150717d,39aeb48f0017,Самарская область,Самара,Для дома и дачи,Мебель и интерьер,Другое,NaN,NaN,Стойка для Одежды,"Стойка для одежды, под вешалки. С бутика.",3000.0,19,2017-03-26,Private,79c9392cc51a9c81c6eb91eceb8e552171db39d7142700...,692.0,0.00000
2,ba83aefab5dc,91e2f88dd6e3,Ростовская область,Ростов-на-Дону,Бытовая электроника,Аудио и видео,"Видео, DVD и Blu-ray плееры",NaN,NaN,Philips bluray,"В хорошем состоянии, домашний кинотеатр с blu ...",4000.0,9,2017-03-20,Private,b7f250ee3f39e1fedd77c141f273703f4a9be59db4b48a...,3032.0,0.43177
3,02996f1dd2ea,bf5cccea572d,Татарстан,Набережные Челны,Личные вещи,Товары для детей и игрушки,Автомобильные кресла,NaN,NaN,Автокресло,Продам кресло от0-25кг,2200.0,286,2017-03-25,Company,e6ef97e0725637ea84e3d203e82dadb43ed3cc0a1c8413...,796.0,0.80323
4,7c90be56d2ab,ef50846afc0b,Волгоградская область,Волгоград,Транспорт,Автомобили,С пробегом,ВАЗ (LADA),2110,"ВАЗ 2110, 2003",Все вопросы по телефону.,40000.0,3,2017-03-16,Private,54a687a3a0fc1d68aed99bdaaf551c5c70b761b16fd0a2...,2264.0,0.20797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,401d5fa8e55d,b5fe6a389cc4,Ярославская область,Ярославль,Хобби и отдых,Спорт и отдых,Игры с мячом,NaN,NaN,Продам бутсы Adidas,продам бутсы в отличном состоянии.отыграл 3 тр...,NaN,27,2017-03-27,Private,7c640fb4b6b4066c54e082193b66bedaedfee5e4d12975...,640.0,0.00000
996,4b136de2c16a,f57df929a284,Воронежская область,Воронеж,Бытовая электроника,"Игры, приставки и программы",Игры для приставок,NaN,NaN,Продам диск lara croft на psp,NaN,350.0,142,2017-03-27,Company,0a7686a2e05ca2dc0470e550f1f03b1eddee7919d363ca...,2888.0,0.00000
997,a65090f39f50,8673d0037023,Свердловская область,Монетный,Недвижимость,"Дома, дачи, коттеджи",Продам,Коттедж,NaN,Коттедж 150 м² на участке 12 сот.,Продается чудесный коттедж в экологически чист...,5900000.0,5830,2017-03-18,Shop,9061df217dd8f2b338e2645d52b09af6143677d011002a...,1376.0,0.07725
998,53e0aa75cecd,fbfe3f73586d,Башкортостан,Ишимбай,Транспорт,Автомобили,С пробегом,Hyundai,i30,"Hyundai i30, 2012",Продается автомобиль Hyundai i30. Был куплен ...,550000.0,1,2017-03-20,Private,c7fe551884576cb8b1bb9bbfe216b3e0b437d6b2208deb...,1118.0,0.10521
999,211a7d242f97,b3e017bd61eb,Самарская область,Самара,Для дома и дачи,Ремонт и строительство,Окна и балконы,NaN,NaN,Породам окно,"Глухое 1кам32 с.пакет, ш650в1440. Новое не под...",2000.0,32,2017-03-24,Private,a68483a58dfbf3b7abf95dfe623651aa45dc211dbb2992...,1405.0,0.00000

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   item_id               1000 non-null   object
 1   user_id               1000 non-null   object
 2   region                1000 non-null   object
 3   city                  1000 non-null   object
 4   parent_category_name  1000 non-null   object
 5   category_name         1000 non-null   object
 6   param_1               956 non-null    object
 7   param_2               553 non-null    object
 8   param_3               406 non-null    object
 9   title                 1000 non-null   object
 10  description           933 non-null    object
 11  price                 935 non-null    float64
 12  item_seq_number       1000 non-null   int64
 13  activation_date       1000 non-null   object
 14  user_type             1000 non-null   object
 15  image                 921 non-null    object
 16  image_top_1           921 non-null    float64
 17  deal_probability      1000 non-null   float64
dtypes: float64(3), int64(1), object(14)
memory usage: 140.8+ KB

In [25]:
data.isnull().sum()

item_id                   0
user_id                   0
region                    0
city                      0
parent_category_name      0
category_name             0
param_1                  44
param_2                 447
param_3                 594
title                     0
description              67
price                    65
item_seq_number           0
activation_date           0
user_type                 0
image                    79
image_top_1              79
deal_probability          0
dtype: int64

In [34]:
data["param_1"] = data["param_1"].fillna(data["param_1"].mode()[0])
data["param_2"] = data["param_2"].fillna(data["param_2"].mode()[0])
data["param_3"] = data["param_3"].fillna(data["param_3"].mode()[0])
data["description"] = data["description"].fillna(data["description"].mode()[0])
data["price"] = data["price"].fillna(data["price"].mode()[0])
data["image"] = data["image"].fillna(data["image"].mode()[0])
data["image_top_1"] = data["image_top_1"].fillna(data["image_top_1"].mean())

In [35]:
data.isnull().sum()

item_id                 0
user_id                 0
region                  0
city                    0
parent_category_name    0
category_name           0
param_1                 0
param_2                 0
param_3                 0
title                   0
description             0
price                   0
item_seq_number         0
activation_date         0
user_type               0
image                   0
image_top_1             0
deal_probability        0
dtype: int64

In [37]:
expensive_items = data[data["price"] > 1000]
expensive_items

,item_id,user_id,region,city,parent_category_name,category_name,param_1,param_2,param_3,title,description,price,item_seq_number,activation_date,user_type,image,image_top_1,deal_probability
1,2dac0150717d,39aeb48f0017,Самарская область,Самара,Для дома и дачи,Мебель и интерьер,Другое,Обувь,42–44 (S),Стойка для Одежды,"Стойка для одежды, под вешалки. С бутика.",3000.0,19,2017-03-26,Private,79c9392cc51a9c81c6eb91eceb8e552171db39d7142700...,692.000000,0.00000
2,ba83aefab5dc,91e2f88dd6e3,Ростовская область,Ростов-на-Дону,Бытовая электроника,Аудио и видео,"Видео, DVD и Blu-ray плееры",Обувь,42–44 (S),Philips bluray,"В хорошем состоянии, домашний кинотеатр с blu ...",4000.0,9,2017-03-20,Private,b7f250ee3f39e1fedd77c141f273703f4a9be59db4b48a...,3032.000000,0.43177
3,02996f1dd2ea,bf5cccea572d,Татарстан,Набережные Челны,Личные вещи,Товары для детей и игрушки,Автомобильные кресла,Обувь,42–44 (S),Автокресло,Продам кресло от0-25кг,2200.0,286,2017-03-25,Company,e6ef97e0725637ea84e3d203e82dadb43ed3cc0a1c8413...,796.000000,0.80323
4,7c90be56d2ab,ef50846afc0b,Волгоградская область,Волгоград,Транспорт,Автомобили,С пробегом,ВАЗ (LADA),2110,"ВАЗ 2110, 2003",Все вопросы по телефону.,40000.0,3,2017-03-16,Private,54a687a3a0fc1d68aed99bdaaf551c5c70b761b16fd0a2...,2264.000000,0.20797
5,51e0962387f7,bbfad0b1ad0a,Татарстан,Чистополь,Личные вещи,Товары для детей и игрушки,Автомобильные кресла,Обувь,42–44 (S),Авто люлька,В хорошем состоянии,1300.0,9,2017-03-28,Private,eb6ad1231c59d3dc7e4020e724ffe8e4d302023ddcbb99...,796.000000,0.80323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,442432ea065b,ef2765b65cae,Воронежская область,Воронеж,Бытовая электроника,Телефоны,Номера и SIM-карты,Обувь,42–44 (S),Красивый номер мегафон,Продам красивый номер:восемь девятьсот двадцат...,12000.0,4,2017-03-16,Private,052af7590b60e0fe85c0e2130b6d0745c2c54e14ed3786...,1234.806732,0.00000
992,5ca79042c44d,1f120cac985a,Краснодарский край,Анапа,Личные вещи,"Одежда, обувь, аксессуары",Женская одежда,Платья и юбки,40–42 (XS),Юбка Kira Plastinina,"В идеальном состоянии, на талию 160-165",2300.0,26,2017-03-22,Private,131ae8c08c2ad30fc342cfbada3db3e2356cd7fe79a9ec...,81.000000,0.00000
997,a65090f39f50,8673d0037023,Свердловская область,Монетный,Недвижимость,"Дома, дачи, коттеджи",Продам,Коттедж,42–44 (S),Коттедж 150 м² на участке 12 сот.,Продается чудесный коттедж в экологически чист...,5900000.0,5830,2017-03-18,Shop,9061df217dd8f2b338e2645d52b09af6143677d011002a...,1376.000000,0.07725
998,53e0aa75cecd,fbfe3f73586d,Башкортостан,Ишимбай,Транспорт,Автомобили,С пробегом,Hyundai,i30,"Hyundai i30, 2012",Продается автомобиль Hyundai i30. Был куплен ...,550000.0,1,2017-03-20,Private,c7fe551884576cb8b1bb9bbfe216b3e0b437d6b2208deb...,1118.000000,0.10521
999,211a7d242f97,b3e017bd61eb,Самарская область,Самара,Для дома и дачи,Ремонт и строительство,Окна и балконы,Обувь,42–44 (S),Породам окно,"Глухое 1кам32 с.пакет, ш650в1440. Новое не под...",2000.0,32,2017-03-24,Private,a68483a58dfbf3b7abf95dfe623651aa45dc211dbb2992...,1405.000000,0.00000

In [40]:
print("data.shape = ",data.shape)
print("expensive_items.shape = ",expensive_items.shape)

data.shape =  (1000, 18)
expensive_items.shape =  (480, 18)

In [42]:
import numpy as np
items_with_price = data[data['price'] != np.nan]
items_with_price

,item_id,user_id,region,city,parent_category_name,category_name,param_1,param_2,param_3,title,description,price,item_seq_number,activation_date,user_type,image,image_top_1,deal_probability
0,b912c3c6a6ad,e00f8ff2eaf9,Свердловская область,Екатеринбург,Личные вещи,Товары для детей и игрушки,Постельные принадлежности,Обувь,42–44 (S),Кокоби(кокон для сна),"Кокон для сна малыша,пользовались меньше месяц...",400.0,2,2017-03-28,Private,d10c7e016e03247a3bf2d13348fe959fe6f436c1caf64c...,1008.0,0.12789
1,2dac0150717d,39aeb48f0017,Самарская область,Самара,Для дома и дачи,Мебель и интерьер,Другое,Обувь,42–44 (S),Стойка для Одежды,"Стойка для одежды, под вешалки. С бутика.",3000.0,19,2017-03-26,Private,79c9392cc51a9c81c6eb91eceb8e552171db39d7142700...,692.0,0.00000
2,ba83aefab5dc,91e2f88dd6e3,Ростовская область,Ростов-на-Дону,Бытовая электроника,Аудио и видео,"Видео, DVD и Blu-ray плееры",Обувь,42–44 (S),Philips bluray,"В хорошем состоянии, домашний кинотеатр с blu ...",4000.0,9,2017-03-20,Private,b7f250ee3f39e1fedd77c141f273703f4a9be59db4b48a...,3032.0,0.43177
3,02996f1dd2ea,bf5cccea572d,Татарстан,Набережные Челны,Личные вещи,Товары для детей и игрушки,Автомобильные кресла,Обувь,42–44 (S),Автокресло,Продам кресло от0-25кг,2200.0,286,2017-03-25,Company,e6ef97e0725637ea84e3d203e82dadb43ed3cc0a1c8413...,796.0,0.80323
4,7c90be56d2ab,ef50846afc0b,Волгоградская область,Волгоград,Транспорт,Автомобили,С пробегом,ВАЗ (LADA),2110,"ВАЗ 2110, 2003",Все вопросы по телефону.,40000.0,3,2017-03-16,Private,54a687a3a0fc1d68aed99bdaaf551c5c70b761b16fd0a2...,2264.0,0.20797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,401d5fa8e55d,b5fe6a389cc4,Ярославская область,Ярославль,Хобби и отдых,Спорт и отдых,Игры с мячом,Обувь,42–44 (S),Продам бутсы Adidas,продам бутсы в отличном состоянии.отыграл 3 тр...,500.0,27,2017-03-27,Private,7c640fb4b6b4066c54e082193b66bedaedfee5e4d12975...,640.0,0.00000
996,4b136de2c16a,f57df929a284,Воронежская область,Воронеж,Бытовая электроника,"Игры, приставки и программы",Игры для приставок,Обувь,42–44 (S),Продам диск lara croft на psp,В отличном состоянии,350.0,142,2017-03-27,Company,0a7686a2e05ca2dc0470e550f1f03b1eddee7919d363ca...,2888.0,0.00000
997,a65090f39f50,8673d0037023,Свердловская область,Монетный,Недвижимость,"Дома, дачи, коттеджи",Продам,Коттедж,42–44 (S),Коттедж 150 м² на участке 12 сот.,Продается чудесный коттедж в экологически чист...,5900000.0,5830,2017-03-18,Shop,9061df217dd8f2b338e2645d52b09af6143677d011002a...,1376.0,0.07725
998,53e0aa75cecd,fbfe3f73586d,Башкортостан,Ишимбай,Транспорт,Автомобили,С пробегом,Hyundai,i30,"Hyundai i30, 2012",Продается автомобиль Hyundai i30. Был куплен ...,550000.0,1,2017-03-20,Private,c7fe551884576cb8b1bb9bbfe216b3e0b437d6b2208deb...,1118.0,0.10521
999,211a7d242f97,b3e017bd61eb,Самарская область,Самара,Для дома и дачи,Ремонт и строительство,Окна и балконы,Обувь,42–44 (S),Породам окно,"Глухое 1кам32 с.пакет, ш650в1440. Новое не под...",2000.0,32,2017-03-24,Private,a68483a58dfbf3b7abf95dfe623651aa45dc211dbb2992...,1405.0,0.00000

In [45]:
data.price.isna().sum()

0

In [48]:
data.price.notna().sum()

1000

In [50]:
data['price'].sum(skipna=False)

269921739.0

In [53]:
arr_ts = [0.469112, np.nan, -5.689738, np.nan, -8.916232]
dates = [
    pd.Timestamp('2000-01-31'),
    pd.Timestamp('2000-02-29'),
    pd.Timestamp('2002-07-31'),
    pd.Timestamp('2005-01-31'),
    pd.Timestamp('2008-04-30'),
]

In [55]:
ts = pd.Series(arr_ts, index = dates)
ts

2000-01-31    0.469112
2000-02-29         NaN
2002-07-31   -5.689738
2005-01-31         NaN
2008-04-30   -8.916232
dtype: float64

In [62]:
ts.interpolate()

2000-01-31    0.469112
2000-02-29   -2.610313
2002-07-31   -5.689738
2005-01-31   -7.302985
2008-04-30   -8.916232
dtype: float64

In [63]:
ts.interpolate(method = 'time')

2000-01-31    0.469112
2000-02-29    0.273271
2002-07-31   -5.689738
2005-01-31   -7.095568
2008-04-30   -8.916232
dtype: float64

```python
numbers= [40,50,60,70]
length = 10
if (length > len(numbers)):
    raise IndexError
    print("No Execution")
else:
    print(length)


---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[66], line 4
      2 length = 10
      3 if (length > len(numbers)):
----> 4     raise IndexError
      5     print("No Execution")
      6 else:

IndexError:

```python

def negativecheck(number):
    assert(number >= 0), "OOPS... Negative Number"
    print(number*number)
print(negativecheck(10))
print(negativecheck(-10))



100
None
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[67], line 5
      3     print(number*number)
      4 print(negativecheck(10))
----> 5 print(negativecheck(-10))

Cell In[67], line 2, in negativecheck(number)
      1 def negativecheck(number):
----> 2     assert(number >= 0), "OOPS... Negative Number"
      3     print(number*number)

AssertionError: OOPS... Negative Number

In [69]:
try:
    numerator = 50
    denom = int(input("Enter the denominator:"))
    quotient = numerator/denom
    print(quotient)
    print("Division performed successfully")
except ZeroDivisionError:
    print("Denominator as zero.... not allowed")

Enter the denominator: 0

Denominator as zero.... not allowed

## Multiple Exception

In [73]:
try:
    numerator=50
    denom=int(input("Enter the denominator: "))
    print (numerator/denom)
    print ("Division performed successfully")
except ZeroDivisionError:
    print ("Denominator as ZERO is not allowed")
except ValueError:
    print ("Only INTEGERS should be entered")

Enter the denominator:  cs

Only INTEGERS should be entered

In [77]:
try:
    numerator=50
    denom=int(input("Enter the denominator"))
    quotient=(numerator/denom)
    print ("Division performed successfully")
except ValueError:
    print ("Only INTEGERS should be entered")
except:
    print(" OOPS.....SOME EXCEPTION RAISED")

Enter the denominator zz

Only INTEGERS should be entered

### Use of else clause

In [81]:
try:
    numerator=50
    denom=int(input("Enter the denominator: "))
    print (numerator/denom)
    print ("Division performed successfully")
except ZeroDivisionError:
    print ("Denominator as ZERO is not allowed")
except ValueError:
    print ("Only INTEGERS should be entered")
else:
    print("The result of division operation is ", quotient)

Enter the denominator:  10

5.0
Division performed successfully
The result of division operation is  10.0

In [83]:
try:
    numerator = 50
    denom = int(input("Enter the denominator:"))
    quotient = numerator/denom
    print("Division performed Successfully")
except ZeroDivisionError:
    print("Denominator as zero is not allowed")
except ValueError:
    print("Only Integers should be entered")
else:
    print("The result of division operation is ", quotient)
finally:
    print("Over and Out")

Enter the denominator: 10

Division performed Successfully
The result of division operation is  5.0
Over and Out

Write a program to find if the product of consequetive numbers in a list is x

In [103]:
def check_product(lst, X):
    new_list=[]
    for i in range(1,len(lst)):    
        if ((lst[i] - lst[i-1]) == 1):
            new_list.append(lst[i-1])
            new_list.append(lst[i])
        else:
            for j in range(len(new_list)):
                if (lst[i] - new_list[j]) == 1:
                    new_list.append(lst[i])    
    return new_list
lst = [-6,-5,  6, -4, 120]
X = 210

result = check_product(lst, X)
print(result)
for x in range(len(result)):
    if

[-6, -5, -4]

In [85]:
lst = [-4,5,6,-2,7,120]
X= 210
for i in range(len(lst) - 2):
        if lst[i] + 1 == lst[i + 1] and lst[i + 1] + 1 == lst[i + 2]:
            product = lst[i] * lst[i + 1] * lst[i + 2]
            if product == X:
                return True
    return False

In [ ]:
write a program to find if there is consequetive number ocuuring in a list eg.(5,6,-2,7) is also acceptable but (6,5,-2,7) is not acceptable specific sequence is not mentioned it can be any sequence(1,2,3) or(4,5,6). if it occurs then find the product of 5,6,7 for above example and check if it is equal to X. for eg. in below mentioned list 5*6*7=210 then condition is true
list = [-4,5,6,-2,7,120]
X= 210